[project]
name = "bubble"
version = "0.1.0"
description = "Add your description here"
authors = []
packages = [
    { include = "bubble", from = "src" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.27.2",
    "pytest-trio>=0.8.0",
    "pytest>=8.3.3",
    "rdflib>=7.1.1",
    "replicate>=1.0.3",
    "rich>=13.9.4",
    "trio>=0.27.0",
]

[tool.ruff]
line-length = 76
target-version = "py312"

[tool.ruff.lint.isort]
# Use a single line between direct and from import.
lines-between-types = 1
length-sort = true

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.2",
    "pytest>=8.0.0",
    "pytest-trio>=0.8.0"
]
python-preference = "managed"
python-downloads = "automatic"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
trio_mode = true
