[project]
name = "bubble"
version = "0.1.0"
description = "Add your description here"
authors = []
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "trio==0.27.*",
    # structured concurrency
    "rich==13.*",
    # pretty terminal output
    "httpx==0.*",
    # async HTTP client
    "rdflib==7.*",
    # RDF data access
    "pytest==8.*",
    # testing framework
    "pytest-trio==0.*",
    # async testing with structured concurrency
    "pytest-md-report==0.6.*",
    # reporting for continuous integration
    "replicate==1.*",
    # Replicate SDK (various AI models)
    "openai==1.55.*",
    # OpenAI SDK (GPT-4o, o1, etc)
    "anthropic==0.39.*",
    # Anthropic SDK (Claude, Sonnet, etc)
    "py-xid>=1.0.0",
    "py-machineid>=0.6.0",
    "typer>=0.13.1",
    "pyright>=1.1.389",
    "pytest-watcher>=0.4.3",
    "psutil>=6.1.0",
    "pytest-mock>=3.14.0",
    "mock>=5.1.0",
    "pytest-httpx>=0.34.0",
]

[tool.uv.sources]
# stay current with rdflib
rdflib = { git = "https://github.com/RDFLib/rdflib" } 

# I don't remember but this was necessary at some point for something
httptools = { git = "https://github.com/tacaswell/httptools", branch = "patch-1" }

[build-system]
# I don't know why I have to choose this or what it does,
# but I'll make my best guess on how many releases until it breaks.
requires = ["setuptools >= 61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
# otherwise it complains about non-package directories
include = ["bubble"]

[project.scripts]
bubble = "bubble.main:app"

[tool.ruff]
line-length = 80 # slim fit
target-version = "py313" # I'm not interested in old Python versions

[tool.ruff.lint.isort]
# Use a single line between direct and from import.
lines-between-types = 1
length-sort = true

[tool.uv]
dev-dependencies = [
    "ruff==0.*",
    "pytest==8.*",
    "pytest-trio==0.*" # async testing for trio structured concurrency
]

python-preference = "managed"
python-downloads = "automatic"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
trio_mode = true
md_report = true
md_report_verbose = 1
mock_use_standalone_module = true
