name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13-dev"
        
    - name: Install SWI-Prolog and EYE reasoner
      run: |
        sudo apt-get update
        sudo apt-get install -y swi-prolog
        mkdir -p /tmp/src && cd /tmp/src
        git clone https://github.com/eyereasoner/eye
        cd eye && sudo sh install.sh
        sudo ln -s /opt/eye/bin/eye /usr/bin/eye
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run tests
      run: |
        pytest
